#spring:
#  datasource:
#    url: jdbc:mysql://120.27.128.225:3306/mybatis_redis_cache?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    hikari:
#      #最小空闲连接数
#      minimum-idle: 2
#      # 连接池最大连接数，默认是10
#      maximum-pool-size: 5
#      # 数据库连接超时时间,默认30秒，即30000
#      connection-timeout: 300000
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
#  mapper-locations: classpath*:mapper/*.xml
